### ISSUE TITLE
save point or model

### ISSUE THREAD

**Issue by naseeresmael** [onurctirtir/superresolution-gan#1]
hi @onurctirtir,
thank you for sharing your work with us, i download the dataset, and set batch_size = 12 then begin the trining, after 2 hours i can not find where the trining save point or model, could you please Explain that to me. thank you.

**Comment by onurctirtir** [comment]
You sure training is done? After training, a subdirectory 'model/' will be
created under the directory scripts residing in, and model will be saved
into 'model/'

Thank you for your interest!

5 Eki 2017 2:01 PM tarihinde "naseeresmael" <notifications@github.com>
yazdı:

**Comment by naseeresmael** [comment]
Ok, thank you @onurctirtir for your quick reply.
