### ISSUE TITLE
scale my own photo

### ISSUE THREAD

**Issue by naseeresmael** [onurctirtir/superresolution-gan#2]
hi @onurctirtir, now the trining is finshed, and the test ruselt are mazing ( car dataset test ), could you please explan how to get 2x scale for my own photo, and how to train my own dataset, iam very sorry for wasteing your time.

**Comment by onurctirtir** [comment]
I've just added a new script imgs2npys.py. See it. You can use that script for your own dataset by changing training_set_size and test_set_size parameters.

**Comment by naseeresmael** [comment]
great, thanks alot @onurctirtir.
